
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Este = 4;
  public static final int error = 1;
  public static final int Comienza = 2;
  public static final int Oeste = 3;
  public static final int Norte = 6;
  public static final int Sur = 5;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Comienza",
  "Oeste",
  "Este",
  "Sur",
  "Norte"
  };
}

